[build]
  command = "npm install && echo 'Deploying static site and functions...'"
  functions = "netlify/functions"
  publish = "."

[[redirects]]
  from = "/create-checkout-session"
  to = "/.netlify/functions/create-checkout-session"
  status = 200

[dev]
  framework = "#custom"
  command = "npm run dev"

